#!/usr/bin/env bash
#### KGB Install Module
####
#### Written by Stephan Wendel aka KwadFan <me@stephanwe.de>
#### Copyright 2022 - till today
#### https://github.com/mainsail-crew/MainsailOS
####
#### This File is distributed under GPLv3
####


# shellcheck disable=all

# KGB repo
[[ -n "$KGB_REPO_SHIP" ]] || KGB_REPO_SHIP="https://github.com/Low-Frequency/Klipper-Git-Backup.git"
[[ -n "$KGB_REPO_BRANCH" ]] || KGB_REPO_BRANCH="main"

# Add to $PATH ? (1: yes, 0: no)
[[ -n "$KGB_ADD_TO_PATH" ]] || KGB_ADD_TO_PATH="1"
