#!/usr/bin/env bash
#### Klipper TMC Autotune Install Module
####
#### Written by Matthäus Szturc <MSzturc@gmail.com>
#### Copyright 2024
####
#### This File is distributed under GPLv3
####

#### All Credits for his great tool
#### https://github.com/andrewmcgr/klipper_tmc_autotune

# shellcheck disable=all

# AUTOTUNE repo
[[ -n "$AUTOTUNE_REPO_SHIP" ]] || AUTOTUNE_REPO_SHIP="https://github.com/MSzturc/klipper_tmc_autotune.git"
[[ -n "$AUTOTUNE_REPO_BRANCH" ]] || AUTOTUNE_REPO_BRANCH="main"
