#!/usr/bin/env bash
#### KLIPPAIN Install Module
####
#### Written by Stephan Wendel aka KwadFan <me@stephanwe.de>
#### Copyright 2022 - till today
####
#### This File is distributed under GPLv3
####

#### All Credits to th33xitus for his great tool
#### https://github.com/th33xitus/klippain

# shellcheck enable=requires-variable-braces

# Error handling
set -Ee

# shellcheck disable=SC1091
source /common.sh
install_cleanup_trap


echo_green "Installing sonar ..."

## Step 1: Force apt update
apt-get update --allow-releaseinfo-change

## Step 2: Make sure 'git' is installed!
check_install_pkgs git

## Step 3: Move to Home Dir as WorkingDirectoy
pushd "/home/${BASE_USER}" &> /dev/null || exit 1

## Step 4: clone KLIPPAIN repo
echo_green "Clone KLIPPAIN repository ..."
gitclone KLIPPAIN_REPO klippain

## Step 5: Link install.sh in /usr/local/bin as klippain-install
if [[ ${KLIPPAIN_ADD_TO_PATH} = "1" ]]; then
    echo_green "Add klippain to PATH ..."
    sudo ln -s "/home/${BASE_USER}/klippain/install.sh" "/usr/local/bin/klippain-install"
fi

## Finish
echo_green "Installing KLIPPAIN ... DONE!"
