#!/usr/bin/env bash
#### Klipper LED-Effect Install Module
####
#### Written by Stephan Wendel aka KwadFan <me@stephanwe.de>
#### Copyright 2022 - till today
#### https://github.com/mainsail-crew/MainsailOS
####
#### This File is distributed under GPLv3
####


# shellcheck disable=all

# MOTD repo
[[ -n "$KLIPPER_LED_EFFECT_REPO_SHIP" ]] || KLIPPER_LED_EFFECT_REPO_SHIP="https://github.com/julianschill/klipper-led_effect.git"
[[ -n "$KLIPPER_LED_EFFECT_REPO_BRANCH" ]] || KLIPPER_LED_EFFECT_REPO_BRANCH="main"

# Add to $PATH ? (1: yes, 0: no)
[[ -n "$KLIPPER_LED_EFFECT_ADD_TO_PATH" ]] || KLIPPER_LED_EFFECT_ADD_TO_PATH="1"
