#!/usr/bin/env bash
#### Klipper LED-Effect Install Module
####
#### Written by Stephan Wendel aka KwadFan <me@stephanwe.de>
#### Copyright 2022 - till today
####
#### This File is distributed under GPLv3
####

#### All Credits to th33xitus for his great tool
#### https://github.com/th33xitus/klipper_led_effect

# shellcheck enable=requires-variable-braces

# Error handling
set -Ee

# shellcheck disable=SC1091
source /common.sh
install_cleanup_trap


echo_green "Installing Klipper LED-Effect ..."

## Step 1: Force apt update
apt-get update --allow-releaseinfo-change

## Step 2: Make sure 'git' is installed!
check_install_pkgs git

## Step 3: Move to Home Dir as WorkingDirectoy
pushd "/home/${BASE_USER}" &> /dev/null || exit 1

## Step 4: clone KLIPPER_LED_EFFECT repo
echo_green "Clone KLIPPER_LED_EFFECT repository ..."
gitclone KLIPPER_MOTD_REPO klipper_led_effect

## Step 5: Link install.sh in /usr/local/bin as klipper_led_effect-setup
if [[ ${KLIPPER_MOTD_ADD_TO_PATH} = "1" ]]; then
    echo_green "Add klipper_led_effect to PATH ..."
    ls -la /home/"${BASE_USER}"/klipper_led_effect
    sudo chmod +x /home/"${BASE_USER}"/klipper_led_effect/install-led_effect.sh
    sudo ln -s /home/"${BASE_USER}"/klipper_led_effect/setup.sh /usr/local/bin/led_effect
    ## Step 6: Install systemd service
    echo_green "Installing Klipper LED-effect service ..."
    sudo /home/"${BASE_USER}"/klipper_led_effect/install-led_effect.sh
fi




## Finish
echo_green "Installing Klipper LED-Effect ... DONE!"
