#!/usr/bin/env bash
#### BDSENSOR Install Module
####
#### Written by Matthäus Szturc <MSzturc@gmail.com>
#### Copyright 2022 - till today
####
#### This File is distributed under GPLv3
####

# shellcheck disable=all

# BDSENSOR repo
[[ -n "$BDSENSOR_REPO_SHIP" ]] || BDSENSOR_REPO_SHIP="https://github.com/markniu/Bed_Distance_sensor.git"
[[ -n "$BDSENSOR_REPO_BRANCH" ]] || BDSENSOR_REPO_BRANCH="new"