#!/usr/bin/env bash
#### BDSENSOR Install Module
####
#### Written by Matthäus Szturc <MSzturc@gmail.com>
#### Copyright 2022 - till today
####
#### This File is distributed under GPLv3
####

# Source error handling, leave this in place
set -EeX

## Set LC_ALL to prevent errors
export LC_ALL=C

# Set DEBIAN_FRONTEND to noninteractive
if [[ "${DEBIAN_FRONTEND}" != "noninteractive" ]]; then
    export DEBIAN_FRONTEND=noninteractive
fi

# Source CustomPIOS common.sh
# shellcheck disable=SC1091
source /common.sh
install_cleanup_trap

echo_green "Installing BDSensor ..."

## Force apt update
apt-get update
## Make sure 'git' is installed!
check_install_pkgs git

## Step 1: Move to Home Dir as WorkingDirectoy
pushd "/home/${BASE_USER}" &> /dev/null || exit 1

## Step 2: clone BDSensor repo
gitclone BDSENSOR_REPO Bed_Distance_sensor

## Step 3: Move to BDSensor klipper as working directory
pushd "/home/${BASE_USER}/Bed_Distance_sensor/klipper" &> /dev/null || exit 1

## Step 4: Run BDSensor install routine
echo_green "Launch BDSensor install routine ..."
sudo -u "${BASE_USER}" "/home/${BASE_USER}/Bed_Distance_sensor/klipper/install_BDsensor.sh"

## Step 5: Leave BDSensor klipper folder
popd &> /dev/null || exit 1

## Finish
echo_green "Installing BDSensor ... DONE!"