#!/usr/bin/env bash
#### KLIPPER-MOTD Install Module
####
#### Written by Stephan Wendel aka KwadFan <me@stephanwe.de>
#### Copyright 2022 - till today
#### https://github.com/mainsail-crew/MainsailOS
####
#### This File is distributed under GPLv3
####


# shellcheck disable=all

# MOTD repo
[[ -n "$KLIPPER_MOTD_REPO_SHIP" ]] || KLIPPER_MOTD_REPO_SHIP="https://github.com/tomaski/klipper-motd.git"
[[ -n "$KLIPPER_MOTD_REPO_BRANCH" ]] || KLIPPER_MOTD_REPO_BRANCH="main"

# Add to $PATH ? (1: yes, 0: no)
[[ -n "$KLIPPER_MOTD_ADD_TO_PATH" ]] || KLIPPER_MOTD_ADD_TO_PATH="1"
