#!/usr/bin/env bash
#### KLIPPER-MOTD Install Module
####
#### Written by Stephan Wendel aka KwadFan <me@stephanwe.de>
#### Copyright 2022 - till today
####
#### This File is distributed under GPLv3
####

#### All Credits to th33xitus for his great tool
#### https://github.com/th33xitus/klipper-motd

# shellcheck enable=requires-variable-braces

# Error handling
set -Ee

# shellcheck disable=SC1091
source /common.sh
install_cleanup_trap


echo_green "Installing sonar ..."

## Step 1: Force apt update
apt-get update --allow-releaseinfo-change

## Step 2: Make sure 'git' is installed!
check_install_pkgs git

## Step 3: Move to Home Dir as WorkingDirectoy
pushd "/home/${BASE_USER}" &> /dev/null || exit 1

## Step 4: clone KLIPPER-MOTD repo
echo_green "Clone KLIPPER-MOTD repository ..."
gitclone KLIPPER_MOTD_REPO klipper-motd

## Step 5: Link install.sh in /usr/local/bin as klipper-motd-setup
if [[ ${KLIPPER_MOTD_ADD_TO_PATH} = "1" ]]; then
    echo_green "Add klipper-motd to PATH ..."
    sudo chmod +x /home/"${BASE_USER}"/klipper-motd/setup.sh
    sudo ln -s /home/"${BASE_USER}"/klipper-motd/setup.sh /usr/local/bin/motd-setup
    sudo chmod +x /home/"${BASE_USER}"/klipper-motd/motd-config
    sudo ln -s "/home/"${BASE_USER}"/klipper-motd/motd-config /usr/local/bin/motd-config
fi

## Step 6: Install systemd service
echo_green "Installing klipper-motd service ..."
sudo /home/${BASE_USER}/klipper-motd/setup.sh --install

## Step 7: Set MOTD theme to Voron
echo_green "Update klipper-motd to Voron theme ..."
sudo sed -i "/OS_FLAVOR=/cOS_FLAVOR=\'voron\'" /etc/update-motd.d/10-klipper-motd

## Finish
echo_green "Installing KLIPPER-MOTD ... DONE!"
