#!/usr/bin/env bash
#### KLIPPER_TMC_AUTOTUNE Install Module
####
#### Written by Stephan Wendel aka KwadFan <me@stephanwe.de>
#### Copyright 2022 - till today
#### https://github.com/mainsail-crew/MainsailOS
####
#### This File is distributed under GPLv3
####


# shellcheck disable=all

# KLIPPER_TMC_AUTOTUNE repo
[[ -n "$KLIPPER_TMC_AUTOTUNE_REPO_SHIP" ]] || KLIPPER_TMC_AUTOTUNE_REPO_SHIP="https://github.com/andrewmcgr/klipper_tmc_autotune.git"
[[ -n "$KLIPPER_TMC_AUTOTUNE_REPO_BRANCH" ]] || KLIPPER_TMC_AUTOTUNE_REPO_BRANCH="develop"

# Add to $PATH ? (1: yes, 0: no)
[[ -n "$KLIPPER_TMC_AUTOTUNE_ADD_TO_PATH" ]] || KLIPPER_TMC_AUTOTUNE_ADD_TO_PATH="1"
