#!/usr/bin/env bash
#### KLIPPER_TMC_AUTOTUNE Install Module
####
#### Written by Stephan Wendel aka KwadFan <me@stephanwe.de>
#### Copyright 2022 - till today
####
#### This File is distributed under GPLv3
####

#### https://github.com/andrewmcgr/klipper_tmc_autotune

# shellcheck enable=requires-variable-braces

# Error handling
set -Ee

# shellcheck disable=SC1091
source /common.sh
install_cleanup_trap


echo_green "Installing Klipper TMC Autotune ..."

## Step 1: Force apt update
apt-get update --allow-releaseinfo-change

## Step 2: Make sure 'git' is installed!
check_install_pkgs git

## Step 3: Move to Home Dir as WorkingDirectoy
pushd /home/"${BASE_USER}" &> /dev/null || exit 1

## Step 4: clone KLIPPER_TMC_AUTOTUNE repo
echo_green "Clone KLIPPER_TMC_AUTOTUNE repository ..."
#gitclone KLIPPER_TMC_AUTOTUNE_REPO klipper_tmc_autotune

## Step 5: Link install.sh in /usr/local/bin as klipper_tmc_autotune-install
#if [[ ${KLIPPER_TMC_AUTOTUNE_ADD_TO_PATH} = "1" ]]; then
#    echo_green "Add klipper_tmc_autotune to PATH ..."
#    sudo ln -s /home/"${BASE_USER}"/klipper_tmc_autotune/install.sh /usr/local/bin/klipper_tmc_autotune-install
#fi

sudo -u "${BASE_USER}" wget -O - https://raw.githubusercontent.com/andrewmcgr/klipper_tmc_autotune/main/install.sh | sudo -u "${BASE_USER} bash

## Finish
echo_green "Installing Klipper TMC Autotune ... DONE!"
