#!/usr/bin/env bash
# Shebang for better file detection
# shellcheck enable=require-variable-braces

get_img_name() {
    local -a types
    types=(zip 7z xz)
    if [ -n "${DIST_PATH}" ]; then
        for i in "${types[@]}"; do
            find "${DIST_PATH}/image/" -type f -name "*.${i}" -printf "%p\n"
        done
    fi

    if [ -z "${DIST_PATH}" ]; then
        echo ""
    fi
}

DIST_VERSION="0.5.0"
BASE_ZIP_IMG="$(get_img_name)"
DIST_NAME="THEOS"

BASE_BOOT_MOUNT_PATH=boot

# export Variables
export BASE_BOOT_MOUNT_PATH
export DIST_NAME
export DIST_VERSION
export BASE_ZIP_IMG

### JSON sniplet Setup
### NOTE: Please see all config files for setup variables!!!
# shellcheck disable=SC2034
JSON_PRETTY_NAME="THEOS"
# shellcheck disable=SC2034
JSON_DESCRIPTION="A OS image with Klipper/Moonraker/Mainsail preinstalled for your T100/T250 3d Printer"
# shellcheck disable=SC2034
JSON_ICON_URL="https://raw.githubusercontent.com/MSzturc/THEOS/develop/.github/sdcard-logo.png"
# shellcheck disable=SC2034
JSON_INIT_FORMAT="none"
# shellcheck disable=SC2034
JSON_SUPPORTED_SBC=""
# JSON_SUPPORTED_SBC="pi1-32bit pi2-32bit pi3-32bit pi3-64bit pi4-32bit pi4-64bit pi5-64bit"
