#!/usr/bin/env bash
#### KGB Install Module
####
#### Written by Stephan Wendel aka KwadFan <me@stephanwe.de>
#### Copyright 2022 - till today
####
#### This File is distributed under GPLv3
####

#### https://github.com/andrewmcgr/kgb

# shellcheck enable=requires-variable-braces

# Error handling
set -Ee

# shellcheck disable=SC1091
source /common.sh
install_cleanup_trap


echo_green "Installing Klipper-Git-Backup ..."

## Step 1: Force apt update
apt-get update --allow-releaseinfo-change

## Step 2: Make sure 'git' is installed!
check_install_pkgs git

## Step 3: Move to Home Dir as WorkingDirectoy
pushd "/home/${BASE_USER}" &> /dev/null || exit 1

## Step 4: clone KGB repo
echo_green "Clone KGB repository ..."
gitclone KGB_REPO kgb

## Step 5: Link install.sh in /usr/local/bin as kgb-install
if [[ ${KGB_ADD_TO_PATH} = "1" ]]; then
    echo_green "Add kgb to PATH ..."
    sudo ln -s "/home/${BASE_USER}/kgb/kgb.sh" "/usr/local/bin/kgb"
    mkdir "/home/${BASE_USER}/.secrets"
    chmod 700 "/home/${BASE_USER}/.secrets"
    touch "/home/${BASE_USER}/.secrets/gh-token"
    chmod 600 "/home/${BASE_USER}/.secrets/gh-token"
fi

## Finish
echo_green "Installing Klipper-Git-Backup ... DONE!"
