#!/usr/bin/env bash
#### HAPPYHARE Install Module
####
#### Written by Stephan Wendel aka KwadFan <me@stephanwe.de>
#### Copyright 2022 - till today
####
#### This File is distributed under GPLv3
####

#### https://github.com/andrewmcgr/happyhare

# shellcheck enable=requires-variable-braces

# Error handling
set -Ee

# shellcheck disable=SC1091
source /common.sh
install_cleanup_trap


echo_green "Installing Happy Hare ..."

## Step 1: Force apt update
apt-get update --allow-releaseinfo-change

## Step 2: Make sure 'git' is installed!
check_install_pkgs git

## Step 3: Move to Home Dir as WorkingDirectoy
pushd /home/"${BASE_USER}" &> /dev/null || exit 1

## Step 4: clone HAPPYHARE repo
echo_green "Clone HAPPYHARE repository ..."
gitclone HAPPYHARE_REPO happy-hare

## Step 5: Link install.sh in /usr/local/bin as happyhare-install
if [[ ${HAPPYHARE_ADD_TO_PATH} = "1" ]]; then
    echo_green "Add happyhare to PATH ..."
    sudo ln -s /home/"${BASE_USER}"/happy-hare/install.sh /usr/local/bin/happy-hare-install
fi

## Finish
echo_green "Installing Happy Hare ... DONE!"
